### ISSUE TITLE
Need to update constructor

### ISSUE THREAD

**Issue by jverzani** [neveritt/PolynomialMatrices.jl#17]
As of the last version of Polynomials a small change makes your tests break. Likely it is in the constructor (https://github.com/neveritt/PolynomialMatrices.jl/blob/master/src/type.jl#L15) where the type of the polynomial coefficients is no longer given by eltype(p), but rather eltype(coeffs(p)). (We added an iterator interface to polynomial objects and this implied this change.) Cf https://github.com/JuliaLang/METADATA.jl/pull/8528#issuecomment-290308421 for some commentary.

**Comment by tkelman** [comment]
Guess we should upper-bound the past versions for this too.
