### ISSUE TITLE
A test will fail with a change in Polynomials.jl

### ISSUE THREAD

**Issue by jverzani** [neveritt/PolynomialMatrices.jl#27]
This test failure:

```
 Expression: degree(pm3[idx]) == 0
   Evaluated: -1 == 0
```

will occur when the changes of https://github.com/JuliaMath/Polynomials.jl/commit/1c2c79672e7fa18f14bf0ed7f3f77c1602c94ceb are merged into the released version. The test would need to be changed as `pm3[idx]` is a zero polynomial, so the degree is now -1 and not 0, as before.

**Comment by hurak** [comment]
Corrected.
